### ISSUE TITLE
DynamoDbMoshi.autoDynamoLens doesn't convert values4k objects

### ISSUE THREAD

**Issue by oharaandrew314** [http4k/http4k-connect#156]
`DynamoDbMoshi.autoDynamoLens` doesn't convert values4k objects as you would expect.  For example, if you have a `StringValue` of `foo`, you would expect it to convert to an `AttributeValue.Str`, but it instead converts to an `AttributeValue.Map` (see first test below).  This contrasts with `Attribute<Final>` lenses, which works as expected (see second test below).

```kotlin
    class PersonId private constructor(value: Int): IntValue(value) {
        companion object : IntValueFactory<PersonId>(::PersonId)
    }

    data class Person(
        val id: PersonId,
        val name: String
    )

    @Test
    fun `convert model with value object to Item`() {
        val lens = DynamoDbMoshi.autoDynamoLens<Person>()
        val person = Person(PersonId.of(1), "Patrick")

        val item = Item().with(lens of person)
        assertThat(
            item, equalTo(
                mapOf(
                    AttributeName.of("id") to AttributeValue.Num(1),
                    AttributeName.of("name") to AttributeValue.Str("Patrick")
                )
            )
        )
        // Fail!: Was {id:AttributeValue(M={value=AttributeValue(N=1.0)}), name:AttributeValue(S=Patrick)}
    }

    @Test
    fun `convert value object attribute`() {
        val personIdAttr = Attribute.int().value(PersonId).required("id")

        val personId = PersonId.of(1)
        val attributeValue = personIdAttr.asValue(personId)

        assertThat(attributeValue, equalTo(AttributeValue.Num(1)))
        // Pass!
    }
```

Clearly, `DynamoDbMoshi` is capable of converting manually added `values4k` objects, like `TableName` and `IndexName`, but those are registered manually in that object.  Is there a way to get `DynamoDbMoshi` to convert ALL values4k objects?

**Comment by daviddenton** [comment]
Each values4k object currently needs to be manually configured to be converted. It's possible that we could write a generic converter to do it, but it would need investigation (and I'm not sure the generics would work)

**Comment by oharaandrew314** [comment]
I did find a workaround by defining a custom `AutoMarshalling`, but it's tedious to register each value factory individually.

```
object MyMoshi: ConfigurableMoshi(
    Moshi.Builder()
        .add(MapAdapter)
        .add(ListAdapter)
        .asConfigurable()
        .withStandardMappings()
        .value(Value1)
        .value(Value2)
        .value(Value3)
        .done()
)

val myLens = MyMoshi.autoDynamoLens<MyDto>()
```

Do you typically not use values4k objects in your DTOs either?  Or is it standard practice for you to make custom `AutoMarshalling` objects as you've done for each http4k-connect module.  I've noticed the exact same behaviour when serializing a JSON DTO.  In my projects, I always prefer not to from the standard `AutoMarshalling` instances; for greater consistency.

**Comment by daviddenton** [comment]
We do make a *lot* of use of values4k objects in our DTOs - and you're right - we always define different auto-marshalling instances for each service (and actually each inbound and outbound API - if it's a third party - this allows us to serialise the same object to different formats for different systems - eg. date formats). Pretty much every domain value is represented as a values4k type.

Sharing of custom mappings can be done through extension functions.

**Comment by oharaandrew314** [comment]
Thanks; I'll keep what you said in mind.  Closing.
