### ISSUE TITLE
Amazon Ec2CredentialsProvider delay if not in EC2

### ISSUE THREAD

**Issue by oharaandrew314** [http4k/http4k-connect#200]
The Amazon EC2CredentialsChain takes a long time to fail if not run in EC2. Find a way to short-circuit the failure, without depending on the underlying HTTP backend's timeout settings.

**Comment by daviddenton** [comment]
Is there an environment variable that we can check for, or a local URL we can hit first?

**Comment by oharaandrew314** [comment]
I believe you can check an environment variable, yes.  That would be my preferred solution.

The EC2 Metadata service we're trying and failing to hit is a private IP; but since it doesn't exist in public space, I believe the default http backend just takes a long time to give up on the connection attempt.

**Comment by oharaandrew314** [comment]
The v2 java sdk uses the same timeout mechanism; albeit shorter than the default java client's.  The v2 java sdk's default credentials chain actually puts the ec2 instance metadata provider as last in the chain, which would have avoided the issue I experienced if I had followed suit.  I may put a warning in the code to guide against this mistake.
