### ISSUE TITLE
Amazon CredentialsProvider should include region

### ISSUE THREAD

**Issue by oharaandrew314** [http4k/http4k-connect#201]
There are a few AWS credentials workflows that determine what the client's region should be.  However, http4k-connect ignores this region, and instead requires it to be passed in via env, or manually.  Known scenarios:

- Profile Credentials
- Profile Assume Role
- EC2 Metadata Service

This is especially annoying for EC2 deployments, where the same app can be running on various regions; it's not really a property that should be passed in via static config.

I propose we add an optional `Region` property to `AwsCredentials`, modify the `CredentialsProvider` workflows to add it, and then find a way for the client factories to use it.  This may be difficult, as the `AwsCredentials` retrieval is deferred, but the `Region` must be known on init.

Thoughts?

**Comment by oharaandrew314** [comment]
This is actually the same behaviour as the v2 java sdk.  The real issue is that the v2 java sdk has a default region provider chain.  In that chain, the profile file and ec2 metadata service are consulted.  I will close this issue for now.

**Comment by daviddenton** [comment]
with the EC2 metadata service, it looks like this could be consulted in order to get the region and then inject that value into the environment which is passed to the other adapters? Is this the case for another connect adapter maybe 🤔 

Sorry for not picking this up - it kind of fell off the radar...

**Comment by oharaandrew314** [comment]
Absolutely; I'm envisioning some sort of `RegionProvider` to perform this lookup; as well as improvements to the EC2 Metadata client.  Unfortunately, I had bundled that client into the `ec2credentials` module, which in hindsight, would have been better names `ec2metadata`.
