### ISSUE TITLE
Confusion around ProfileCredentialsProvider

### ISSUE THREAD

**Issue by oharaandrew314** [http4k/http4k-connect#239]
There are two different versions of `CredentialsProvider.Profile`.  One is provided by `http4k-connect-amazon-core`, and one is provided by `http4k-connect-amazon-sts`.  The idea is that if you're certain your profile file doesn't assume a role, you don't need to include the STS module.  But in practice, it's tedious and error-prone to import the correct function when both are on the classpath.

The official AWS SDK simplifies this process by dynamically loading the STS Credentials Provider with reflection, but this may not be suitable for http4k-connect.

I can think of a few potential solutions:

1. Rename the STS variant of `CredentialsProvider.Profile` to `CredentialsProvider.ProfileWithSts`
2. Remove `CredentialsProvider.Profile` from `http4k-connect-amazon-core`; it is only provided by the STS module
3. Do what the official AWS SDK does; use java reflect (not kotlin-reflect) to load STS, if available.  This might go against http4k-connect philosophy, but it would be very simple and familiar to users of the official sdk

Are there any thoughts on which solution to use?

**Comment by daviddenton** [comment]
These two do seem to be doing different things - so I think that renaming is probably a better option if they are both valid use-cases.

Oh, and I'd very much prefer to not copy the behaviour of the SDK. - part of the reason for writing connect was to get away from the "official" magical behaviours.... 😉
