### ISSUE TITLE
Fake SQS does not support JSON request format (breaks AWS SDK usage 2.20.60)

### ISSUE THREAD

**Issue by daviddenton** [http4k/http4k-connect#242]
2.20.60 of the Amazon SDK made the protocol switch from form parameters to JSON payload by default (minor point release!). This has exposed that the FakeSQS (and SQS client) does not use this format as it they currently support the URL encoded form payload only.

It has also broken Localstack apparently.

Tracking this here as we should add support for it, even though technically it will only affect people using the official SDK and the FakeSQS.

**Comment by oharaandrew314** [comment]
This has affected me now.  I'll soon work on a solution for at least `sendMessage`
