### ISSUE TITLE
Fake KMS successfully verifies signatures of other keys

### ISSUE THREAD

**Issue by oharaandrew314** [http4k/http4k-connect#263]
This test passes against real KMS, and fails against fake.  I believe it's because `verify` only checks if the key exists, but then shares the same set of key pairs for all kms keys.

```kotlin
@Test
    fun `key cannot verify signature of another key`() {
        val key1 = kms.createKey(RSA_2048, SIGN_VERIFY).successValue().KeyMetadata.KeyId
        val key2 = kms.createKey(RSA_2048, SIGN_VERIFY).successValue().KeyMetadata.KeyId

        try {
            val message1 = Base64Blob.encode("General Kenobi!")

            val signed = kms.sign(key1, message1, RSASSA_PKCS1_V1_5_SHA_256).successValue()

            val verificationFailure = kms.verify(key2, message1, signed.Signature, RSASSA_PKCS1_V1_5_SHA_256).failureOrNull()
            assertThat(verificationFailure!!.status, equalTo(BAD_REQUEST))
        } finally {
            val key1Deletion = kms.scheduleKeyDeletion(key1, 7).successValue()
            assertThat(key1Deletion.KeyId.toARN().value, endsWith(key1.value))

            val key2Deletion = kms.scheduleKeyDeletion(key2, 7).successValue()
            assertThat(key2Deletion.KeyId.toARN().value, endsWith(key2.value))
        }
    }
```

**Comment by oharaandrew314** [comment]
Is there any particular reason the fake kms opted for real cryptographical algorithms?  Would fake encryption (without the need to pre-generate key pairs) not have done the trick?

If we're to solve this issue, we may have to vend certificates at runtime.

**Comment by daviddenton** [comment]
the original use case for adding real keys was to be able to sign and verify JWTs. We felt that adding a verification which only checked it existed was enough at the time for the happy path cases. we're not building a real KMS after all. 😉 

If there's a good (and easy way) to add what you need then feel free to PR it :)

**Comment by oharaandrew314** [comment]
Yes, I'm making progress with certificate generation.  Is there any particular reason bcprov-jdk15on is used as opposed to 18on?  I don't think it's causing my ECDSA parsing issues; I'm just curious.

**Comment by daviddenton** [comment]
no reason really - we probably just copied the dependencies from somewhere else using the older version. If the tests pass then ship it! 🙃
