### ISSUE TITLE
DynamoDbIndexMapper should support more/all dynamoDb function parameters

### ISSUE THREAD

**Issue by obecker** [http4k/http4k-connect#312]
(Remark: I'm rather new to DynamoDB, so I may not fully understand all of DynamoDB's query features.)

I wanted to use the `ConsistentRead` flag for `DynamoDbIndexMapper.query()` and realized that this is currently not possible.
Looking at the code is should be no big deal to add this parameter.
Furthermore `DynamoDb.queryPaginated()` has also `ProjectionExpression`, `Select`, `ExclusiveStartKey`, and `ReturnConsumedCapacity`, but I'm not sure if these make sense for the typed `DynamoDbIndexMapper`.
And the same applies of course for the other `DynamoDbIndexMapper` functions, i.e. `scan()`, `scanPage()`, and `queryPage()`.

So, could you please add at least the `ConsistentRead` parameter to the `DynamoDbIndexMapper` functions?
I may create a PR if you like.

PS: Wouldn't it make sense to use lower case parameter names, to follow standard Kotlin naming conventions? I guess the serializable `Query` class is the reason for the upper case names, but this can simply be adjusted using `@JsonProperty` annotations. And yes, it's an incompatible change, but nevertheless it would make the code more "natural" for Kotlin developers.

**Comment by oharaandrew314** [comment]
The `DynamoDbIndexMapper` was designed to provide a simplified interface, but I can certainly see the need to include `ConsistentRead`.

**Comment by oharaandrew314** [comment]
I certainly agree the naming convention isn't natural, but it's consistent with all the other modules, and I don't think changing the convention for every module is in the cards (except perhaps for a major release)

**Comment by daviddenton** [comment]
FYI: the naming convention is a by-product of the way in which the objects are marshalled onto the wire - it matches the Amazon requests: 

```
POST / HTTP/1.1
Host: dynamodb.<region>.<domain>;
Accept-Encoding: identity
Content-Length: <PayloadSizeBytes>
User-Agent: <UserAgentString>
Content-Type: application/x-amz-json-1.0
Authorization: AWS4-HMAC-SHA256 Credential=<Credential>, SignedHeaders=<Headers>, Signature=<Signature>
X-Amz-Date: <Date>
X-Amz-Target: DynamoDB_20120810.Scan

{
    "TableName": "Reply",
    "ReturnConsumedCapacity": "TOTAL"
}
```
