### ISSUE TITLE
Feature proposal: provide a query builder for DynamoDb

### ISSUE THREAD

**Issue by obecker** [http4k/http4k-connect#314]
Using DynamoDb's query API (in particular the `DynamoDbIndexMapper` API) I think it's rather cumbersome to build dynamic queries (i.e. queries that depend on the set of passed parameters, for example from an REST API).

I experimented a little bit with this myself and created a small `QueryBuilder` class that enables writing queries like this:

```kotlin
table.primaryIndex().query {
    keyCondition {
        hashAttr eq hashValue
    }
}
```
or
```kotlin
table.primaryIndex().query {
    keyCondition {
        (hashAttr eq hashValue) and (sortAttr le sortValue)
    }
}
```
or
```kotlin
table.primaryIndex().query {
    keyCondition {
        (hashAttr eq hashValue) and (sortAttr gt sortValue)
    }
    filterExpression {
        (statusAttr `in` statusValues) and between(ageAttr, 18, 80) and (fooAttr ne fooValue)
    }
}
```
and a dynamic query would be
```kotlin
table.primaryIndex().query {
    keyCondition {
        val sortCondition = sortValue?.let { sortAttr eq it }
        (hashAttr eq hashValue) and sortCondition // and can handle nulls
    }
    filterExpression {
        val statusCondition = statusValues?.let { statusAttr `in` it }
        val fooCondition = fooValue?.let { fooAttr eq fooValue }
        statusCondition and fooCondition // and can handle nulls
    }
}
```

(all _xyzAttr_ variables are of type ```Attribute<T>```)
The builder takes care of creating the corresponding string expression, attribute names map, and attribute values map.

This is the code of the QueryBuilder: https://gist.github.com/obecker/9afb2479e9a9700fcf4fe76176a7c186

Do you think this is something worth to be added to the `org.http4k:http4k-connect-amazon-dynamodb` lib?

**Comment by oharaandrew314** [comment]
That looks really cool.  I'm sure the team would be happy to receive a PR.  Otherwise, I might nick some of your code to implement it.

**Comment by obecker** [comment]
I'll create a PR with what I've done so far.

**Comment by obecker** [comment]
Finally ... https://github.com/http4k/http4k-connect/pull/320

It is probably not complete yet (see open issues in my commit message), and it requires of course extending the README.md

**Comment by daviddenton** [comment]
Thanks for the contribution @obecker - we'll see what we can do! 🙃
 
@oharaandrew314 As the resident expert on this stuff - fancy castinf your eye overit?

**Comment by oharaandrew314** [comment]
Yeah, I'll look over it sometime.  So as @obecker suggests, it's not quite complete yet.  So what would we do?  Merge it into another branch and merge more additions to it until it's ready?  Or merge this PR into master, but not officially release it?

**Comment by obecker** [comment]
Yeah, a new branch on your side makes the most sense IMHO.

**Comment by obecker** [comment]
And I just realized that the `filterExpression` part is useful for `scan` operations as well.

**Comment by obecker** [comment]
@daviddenton @oharaandrew314 I have extended my proposal, added tests and extended the README, see https://github.com/http4k/http4k-connect/pull/370 (to be merged into the existing branch - I didn't rebase or merge master yet).

Do you have any concerns with the code? Otherwise I think it is ready for the master branch.

Things to note:
- I decided to use Kotlin's naming conventions for the function names (i.e. camelCase) - and not the spelling in the DynamoDB expressions. That means
  * `between(attr, v1, v2)` for `attr BETWEEN v1 and v2`
  * ``attr `in` iterable``  for `attr IN (v1, v2, ...)` (admittedly, that's a little bit ugly)
  * `x and y or not(z)` for `x AND y OR NOT z`
  * `attributeExists`, `attributeNotExists`, `beginsWith` for `attribute_exists`, `attribute_not_exists`, `begins_with`
If you have a strong opinion towards the original upper case and snake_case spelling, then I could live with that. :-)
- The `size` function is still missing. If you read the [formal expression syntax](https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/Expressions.OperatorsAndFunctions.html) then you first think that `size(attr)` is a full filter expression, however then you realize, that `size` needs to be combined with a comparison (`size(attr) > 5`), which would make the code for the DSL much more complex. I wonder if there is a better way for creating such DSLs.

**Comment by oharaandrew314** [comment]
The
```attr `in` iterable```
syntax is pretty unfortunate.  I would suggest either changing them all to UPPERCASE, or changing `in` to `isIn` or `inside`

**Comment by obecker** [comment]
I like `isIn` 😀. Changed.

**Comment by obecker** [comment]
Resolved with https://github.com/http4k/http4k-connect/commit/665649047d936c6684d6748e7434f96b4ff32c0a
