### ISSUE TITLE
FakeDynamoDb should support sparse indexes

### ISSUE THREAD

**Issue by obecker** [http4k/http4k-connect#322]
In particular FakeDynamoDb must not return items on query and scan operations that don't have the hash or sort key attributes set.

**Comment by obecker** [comment]
Could someone please have a look at my PR https://github.com/http4k/http4k-connect/pull/323

I have extended the tests and there are successful with both fake dynamodb and local dynamodb.

Documentation for sparse indexes: https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/bp-indexes-general-sparse-indexes.html

@oharaandrew314 @daviddenton

**Comment by oharaandrew314** [comment]
Sorry, I didn't notice the PR.  I'm not a collaborator, so I don't get nor need notifications by default.
