### ISSUE TITLE
Query algorithm is slight wrong in fake dynamo

### ISSUE THREAD

**Issue by daviddenton** [http4k/http4k-connect#327]
we apply the filter too early, which doesn't match what really happens. We should:

1. Apply the key condition to select items from the table
2. sort by keys
3. select items after the ExclusiveStartKey
4. take Limit items to create a page, and store the last item of the page as the LastEvaluatedKey
5. apply the filter condition to remove items from the page

**Comment by obecker** [comment]
But if the filter is the last step then the resulting page may contain less items than the requested limit (it may even be empty). Moreover the `LastEvaluatedKey` must not be (or contain) null values. Do you have a test or scenario that behaves differently with a local (real) dynamo DB and the fake dynamo DB?

**Comment by daviddenton** [comment]
This is true - but it seems to be how dynamo does it if I'm reading it right:
https://docs.aws.amazon.com/amazondynamodb/latest/APIReference/API_Query.html

**Comment by obecker** [comment]
Ah, you're talking about the filter expression.
(I thought you meant the `filter` I've added [here](https://github.com/http4k/http4k-connect/blob/5e50e8b946ed32dc651c921bc072c3882c3552ff/amazon/dynamodb/fake/src/main/kotlin/org/http4k/connect/amazon/dynamodb/endpoints/query.kt#L18).)
 Yes, indeed - that's what the documentation is saying. Then let's create a test scenario and see what's happening. :-)
 Do you need some support?

**Comment by daviddenton** [comment]
Am snowed at the moment, so yes - any support would be great. I think the changes should be confined to a single file (and also replicated for both scan and query) 🙃
