### ISSUE TITLE
Fake S3 - Support Bucket Request without Host header

### ISSUE THREAD

**Issue by oharaandrew314** [http4k/http4k-connect#332]
If you make a bucket request without the `X-Forwarded-For` or `Host` header, FakeS3 will be unable to determine the bucket of the request, and will return 404.  This is particularly troublesome when working with presigned URLs against in in-memory fake S3.

```kotlin
val response = Request(GET, presignedUrl)
  .let(fakeS3)
// returns 404
```

The current workaround is to add the `Host` header to the request.  I propose we update `Request.subdomain(buckets: Storage<Unit>)` to fall back to the `Uri`'s host, if none of the headers are present.

**Comment by daviddenton** [comment]
yep - sounds like a reasonable idea. Make it so 😉
