### ISSUE TITLE
Amazon Presigner

### ISSUE THREAD

**Issue by oharaandrew314** [http4k/http4k-connect#335]
It would be nice to have some sort of amazon presigner; particularly for S3 GET and PUT.

**Comment by daviddenton** [comment]
It's very possible - I'm sure we've done it before as a filter and using the signing we've already got in the Aws module of the core.

**Comment by oharaandrew314** [comment]
It seems to me the biggest difference between a signed request and pre-signed request is that in a pre-signed request you can customize the validity duration of the signature.  If I can find the documentation (or reverse-engineer one of the SDKs) I should be able to come up with an extension to the `AwsSignatureV4Signer` to add the additional properties.

**Comment by oharaandrew314** [comment]
I think all I need to do is add the `X-Amz-Expires` header to the canonical request, and the `AwsSignatureV4Signer` should work out of the box.

**Comment by oharaandrew314** [comment]
I'm tantalizingly close.  I'm no longer getting `SignatureDoesNotMatch`, but now I'm getting `AccessDenied`, which is frustratingly vague.

**Comment by oharaandrew314** [comment]
Bingo.  I've made a PR in the main http4k repo to add a common pre-signer.

**Comment by daviddenton** [comment]
Closing as releasing in main http4k-aws module

**Comment by oharaandrew314** [comment]
I was going to make an additional helper in this repo, but now that it's possible with the main module, you can close this if you want.

**Comment by daviddenton** [comment]
Intersting - how did you envisage that helper being used?

**Comment by oharaandrew314** [comment]
Something like

`fun presign(action: S3BucketAction<*>): PresignedRequest`

so you could do 

```kotlin
val s3Bucket = S3Bucket.Http("foo", "ca-central-1")
val signed = s3Bucket.presign(GetObject("foo.txt"))
```

**Comment by daviddenton** [comment]
ok - sounds good. If you can do it I'll hold off on the connect release until it's donr

**Comment by oharaandrew314** [comment]
Timing for me will be tight, but I'll try to have it done by your next morning.  If not, I'll be AFK for a week, so you should release without it.

**Comment by daviddenton** [comment]
don;t worry actually - there's nothing else to go in so will hold off :)

**Comment by oharaandrew314** [comment]
This now depends on https://github.com/http4k/http4k/pull/1015

**Comment by daviddenton** [comment]
we're now running with that latest http4k which has that change in it you need 😄

**Comment by daviddenton** [comment]
Merged and awaiting release.
