### ISSUE TITLE
DynamoDbIndexMapper sequence never terminates if underlying scan/query returns an error

### ISSUE THREAD

**Issue by oharaandrew314** [http4k/http4k-connect#342]
If you use the `DynamoDbIndexMapper.scan` or `query` operations, the `Sequence` it returns results in an infinite loop if the underlying `query` or `scan` operation return an error.

This was noticed when running against the `FakeDynamoDb`.  It's unknown whether this can be reproduced with a real opr local DynamoDb.

**Comment by oharaandrew314** [comment]
I can't fully characterize this issue yet.  This is just a placeholder until I can take a closer look at it.

**Comment by daviddenton** [comment]
That's strange - there is a test `pagination stops when failure occurs` to cover that eventuality. 🤔
