### ISSUE TITLE
DynamoDB AutoDynamoLens cannot convert from java set to dynamo set

### ISSUE THREAD

**Issue by oharaandrew314** [http4k/http4k-connect#376]
The DynamoDB `autoDynamoLens` uses JSON to convert from a JVM object to a DynamoDB Item.  This is an elegant solution, however, the conversion to JSON erases the distinction between a java `Set` and `List`.  The `autoDynamoLens` ends up serializing both types into a Dynamo List.  I don't know if it's possible to support this with the current `AutoMarshalling` implementation.  Any method I could think of would require a custom serializer module, which would prevent users from using their own marshaller.

I think the only way to support this would be with a reflective property-aware solution that doesn't rely on JSON.  We could use a stripped down version of the [kotlin-plugin](https://github.com/oharaandrew314/dynamodb-kotlin-module) I built for the official v2 sdk.  This would require kotlin-reflect, but it's a tradeoff one can at least consider.

What do you think?

**Comment by daviddenton** [comment]
The reflective thing is a little anti-http4k-connect TBH. I think I'd rather leave it as a limitation of the lib, unless there is a really good reason to not to. People can always fall back on manually writing the values if they really care about querying the contents of a set (I think this is the only downside really) - which arguably goes counter to the laziness factor of what the auto lens provides.

**Comment by oharaandrew314** [comment]
Closing as duplicate of #369
