### ISSUE TITLE
Bug in DynamoDB query DSL: unable to use key condition "(hashAttr eq val1) and (sortAttr eq val2)"

### ISSUE THREAD

**Issue by obecker** [http4k/http4k-connect#380]
Unfortunately there's a defect in the newly introduced query DSL that prevents me from writing
```kotlin
table.index(refIndex).query {
    keyCondition {
        (ownerAttr eq ownerId) and (refAttr eq refId)
    }
}
```
if the participating hash key and sort key attributes have different types (in the example above owner is a UUID and ref is a string).
The problem is the `refAttr eq refId` part because there is no `eq` function for the sort key attribute.

My original proposal (see [this gist](https://gist.github.com/obecker/9afb2479e9a9700fcf4fe76176a7c186)) didn't have this problem, since `eq` was just defined with a generic type attribute `T`:
```
infix fun <T> Attribute<T>.eq(value: T) = ...
```
So this function is used for both hash key and sort key attributes.

However, in the pull request to support paging and the `queryPage` function, I made the builder aware of the `HashKey` and `SortKey` generic types, so the `eq` function became
```
infix fun Attribute<HashKey>.eq(value: HashKey) = ...
```
and I missed that this function can no longer be invoked for the sort key attribute.

Simply adding a `eq` function for the `SortKey` generic type unfortunately doesn't work. If `HashKey` and `SortKey` happen to be the same type, then the compiler doesn't know which `eq` function to invoke.

I can think of two solutions to fix this:
1. Change the generic type for `eq` back to any `T`, and the type of `KeyCondition.exclusiveStartHashKey` to `Any?`. This requires a type cast in the `DynamoDbQueryBuilder.build()` function (line 308):
```
exclusiveStartHashKey = delegate.keyCondition?.exclusiveStartHashKey as HashKey?
```
You would lose the type safety in the `keyCondition` block, i.e. the compiler won't prohibit using a non-hashKey attribute in the first `eq` condition, so you wouldn't see the mistake until the query is executed. A union type would be a great thing, but afaik there's no support in Kotlin for something like this. (On the other hand, even with the type check you could use the wrong attributes, if they just have the same type as the hash key ...)

2. Use different names for the two `eq` functions. This would solve all compiler type problems, however I have no idea what to call these functions. And it would be a breaking change (for a feature that was released yesterday,  but still ...)

Do you have any opinions on that @daviddenton and @oharaandrew314 (or a third option)? I think option 1 is a pragmatic solution.
Sorry for the trouble.

**Comment by obecker** [comment]
Hey @daviddenton, unless you have a better idea, could you please review and merge https://github.com/http4k/http4k-connect/pull/381? Thank you!

**Comment by daviddenton** [comment]
So I'm wondering with this - can't the ExclusiveStartKey always be a Key (aka Item) instead of this pair which then gets converted to a Key? Then I think we will have all of the options available and there won't be the need for any casting :)

**Comment by daviddenton** [comment]
it will be a break, but I think it would be better if we can make it work 🙃

**Comment by obecker** [comment]
I just had another idea: you mentioned using just `Key` or `Item` would perhaps solve the type cast problem. However, the `DynamoDbTableMapper` already knows about the hash and sort key attributes, that's why a user only needs to provide the actual values. So why should we "go back" to unspecific `Key`s?  However, this led me to an idea: the same approach could be applied to the query DSL as well: instead of allowing any `Attribute`s, in the `keyCondition` we could do a trick that removes the actual attributes from the DSL expression.

My PR should be ready in a couple of minutes.

**Comment by oharaandrew314** [comment]
For what it's worth, I just updated the `DynamoDbIndexMapper` to accept an `ExclusiveStartKey: Key?`.  Getting it to work with the typed keys isn't worth it when the start key for a GSI could actually be 4 attributes total.

**Comment by obecker** [comment]
I'm not sure I understand. Do you mean that in a GSI (with keys x/y) the start key of a query or scan could use the unrelated primary keys (say a/b) of the table? Never thought of that. (And does this even make sense?) However, now that the query DSL no longer needs to remember the hash key, that typing issue I mentioned above is gone.
Nevertheless, I would like to make the `keyCondition` part in the DSL as type-safe as possible, so my second PR will address this (and add the missing `eq` function).

**Comment by oharaandrew314** [comment]
Given this example:

Primary Schema: HASH=id, SORT=date
`names` GSI: HASH=name, SORT=id

If you were to query on the `names` index, then the `LastEvaluatedKey` would contain the `id`, `date`, and `name`.

The issue with the previous interface was that while `table.index(names).query(hashKey=name, exclusiveStartKey=prevId)` can reproduce part of the `ExclusiveStartKey`, it has no idea what to include as the `date` attribute.  I'm sure you could come up with a way to make it work in a typesafe way, but I don't think it's worth the complexity.

**Comment by obecker** [comment]
Ah, thanks for the explanation. Makes perfect sense! I didn't know that DynamoDB returns also the keys of the primary index in the `LastEvaluatedKey`.

**Comment by daviddenton** [comment]
OK - I'm officially a little lost now with the existence of https://github.com/http4k/http4k-connect/pull/387 . Is this fixed now or am I missing something (probably!) 

Thanks for the contributions so fer everyone! :)

**Comment by obecker** [comment]
The [original problem](https://github.com/http4k/http4k-connect/issues/380#issue-2152866825) is still there, however #387 offers a third solution for this.

Instead of adding a (different) function for the sort key (say, `equ`)
```
infix fun Attribute<SortKey>.equ(value: SortKey) = ...
```
or generalizing the existing `eq` function (my previous PR #381) by changing it to
```
infix fun <T : Any> Attribute<T>.eq(value: T) = ...
```
#387 will add two objects `HashKeySubstitute` and `SortKeySubstitute` to the DSL (and two values `hashKey` and `sortKey` in the `keyCondition` context), which will have the `eq` function (and all other allowed functions) defined like this
```
infix fun HashKeySubstitute.eq(value: HashKey) = ...
infix fun SortKeySubstitute.eq(value: SortKey) = ...
```
The implementations will then build a query using the attributes from the schema.

With this, my original example will have to be rewritten as
```
table.index(refIndex).query {
    keyCondition {
        (hashKey eq ownerId) and (sortKey eq refId) // no attributes involved
    }
}
```
This solution solves the naming/typing conflict with the current `eq` function.
It additionally improves the type safety since I cannot use the wrong attributes in the key condition (which would be the case with a generic `eq(value: T)` function). Funny enough, there is already a test for the `count` function, which was successful querying the fake, but it used the wrong index! After the migration to the new syntax the test failed (and so I discovered the bug I introduced previously). 

I made the current functions `@Deprecated` (in case someone is already using the DSL).

Note, for the `filterExpression` the existing solution is unchanged, since the set of attributes that can be used in the filter expression is not defined by the schema (apart from the little detail, that the key attributes mustn't be used, but this is nothing the DSL syntax can solve).
