### ISSUE TITLE
Compatibility in Java

### ISSUE THREAD

**Issue by swapneshran** [http4k/http4k-connect#435]
Could not make it work with Java 11 with maven set up.
Do we need to add kotlin dependencies to the project

**Comment by daviddenton** [comment]
I'm afraid we're going to need to lot more details to get some assistance on this. http4k-connect itself is build and targetted at Java 8 so there should be no problem with using Java 11.

Can I suggest that you ask on the http4k channel in the Kotlin Slack for more immediate support because it feels like an issue which would better be solved there.

**Comment by daviddenton** [comment]
Seems I slightly misunderstood the question so recording and closing this here 🙃  for future generations. 

http4k-connect is definitely NOT designed to be called from Java code as the entire design is based on Kotlin functionality such as extension and operator functions. This makes the developer experience of using the library incredibly bad.

That said, it is not impossible to call it if you are so determined by creating shim classes and referring to extension functions via their static versions:

```kotlin
object ExampleShim {
    @JvmStatic
    fun Http(http: HttpHandler) = Example.Companion.Http(http)
}
```

then:

```java
ublic class UsageFromJava {
    public static void main(String[] args) {
        Example example = ExampleShim.Http(JavaHttpClient.create());

        Result<Echoed, RemoteFailure> result = example.invoke(new Echo("hello"));
        Result<String, RemoteFailure> mapped = ResultKt.map(result, Echoed::getValue);
        Result<String, Exception> orException = ResultKt.mapFailure(mapped, failure -> Exception(failure.message));

        String echoed = ResultKt.orThrow(orException);

        System.out.println(echoed);
    }
}
```
