### ISSUE TITLE
DynamoDb works fine locally, but produces error on lambda.

### ISSUE THREAD

**Issue by Johnathan-Aretos** [http4k/http4k-connect#97]
I'm able to run Dynamodb fine when running Http4k locally, but as soon as I deploy to lambda I get this error here when I try and invoke a dynamodb call. 

`java.lang.NoClassDefFoundError: se/ansman/kotshi/NamedJsonAdapter`
 
I'm currently using Jackson for my json in my app, but it seems like under the hood, Moshi is being used, I wonder if this is causing any issues.

**Comment by daviddenton** [comment]
Strange - you should have the `se.ansman.kotshi:api` dependency bundled into your app - it's a transitive dependency from the dynamo adapter. Can you check if it's included?

Jackson won't be relevant here, so don't worry about that.

**Comment by daviddenton** [comment]
you can see the version is incuded in the maven report for the artifact: https://search.maven.org/artifact/org.http4k/http4k-connect-amazon-dynamodb/3.13.1.0/jar

**Comment by Johnathan-Aretos** [comment]
It's definitely there. I have no issues running locally, but as soon as I get it to a lambda it crashes.

<img width="624" alt="Screen Shot 2021-12-02 at 8 02 30 pm" src="https://user-images.githubusercontent.com/20794199/144390666-ad37e562-8a03-4874-9483-2016cb017e65.png">

**Comment by daviddenton** [comment]
is it in your generated ZIP?

**Comment by daviddenton** [comment]
(also - upgrade to latest connect - just to be sure 😄 )

**Comment by Johnathan-Aretos** [comment]
> is it in your generated ZIP?

How can I see this, I've got the zip. do I just look for the java class?

**Comment by daviddenton** [comment]
inside the ZIP will be a lib directory with the JAR files inside.

**Comment by Johnathan-Aretos** [comment]
I can't see anything resembling that package in the zip.

**Comment by daviddenton** [comment]
aha - I think that's why - your zip is only including the compilation JARs and not the runtime ones.

**Comment by Johnathan-Aretos** [comment]
ah..... there we go, slipped by me, I see the problem. 

This is the fix for anyone needing it 

```
    from compileKotlin
    from processResources
    into('lib') {
        from configurations.implementation
        from configurations.compileClasspath
    }
```
